[package]
name = "tarpaulin-circleci-coveralls"
version = "0.1.0"
authors = ["Takumi ERA <takumi_era@caddi.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
